name: static-web-deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: move to web directory
        run: sudo apt install sshpass && sshpass -p _lucas@admin ssh lucas@192.168.1.20 && echo conect
