name: static-web-deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: bind-repo
        uses: actions/checkout@v3
      - name: delete-dest
        run: rm -R /var/www/html/lucasferrenti.com.ar/public/* || pwd && ls -a
      - name: copy-repo
        run: cp -Rf * /var/www/html/lucasferrenti.com.ar/public/*

