name: static-web-deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: log
        run: sudo su lucas
      - name: log2
        run: echo _lucas@admin
      - name: move to web directory
        run: cd /var/www/html/lucasferrenti.com.ar/public/ && ls -l && pwd && whoiam
      - name: pull changes
        run: git pull origin main
